name: coreapi-app
region: nyc
services:
  - name: coreapi-app-service
    image:
      registry: travistrle
      registry_type: DOCKER_HUB
      repository: core-api
      tag: IMAGE_TAG_PLACE_HOLDER
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /
